### ISSUE TITLE
A more flexible API which does not need the fig

### ISSUE THREAD

**Issue by quantshah** [johannesjmeyer/rsmf#4]
In many cases, I like to make subplots and adjust plots myself and the way I go about it is by modifying the rc_Params list at the top and then never worrying about it through the code. I realised that I can do the same with your code just by calling the parser for the particular latex style at the beginning and reusing its properties as and when I need to:

Consider this as an example perhaps or even changing the the default way you suggest to use the code:

```
from rsmf.revtex import parse as revparse
import matplotlib.pyplot as plt
import numpy as np


revparse(r"\documentclass[aps,pra,twocolumn]{revtex4-1}")


fig, ax = plt.subplots(3, 1, figsize=(formatter.width, 2*formatter.width), sharex=True, sharey=True)
for axis in ax:
    axis.matshow(np.random.random(size=(5, 5)))
    axis.set_ylabel("y-axis")
    axis.set_xlabel("x-axis")
    axis.matshow(np.random.random(size=(5, 5)))

plt.show()


fig, ax = plt.subplots(2, 2, figsize=(formatter.width, formatter.width), sharex=True, sharey=True)
for axis in ax.ravel():
    axis.matshow(np.random.random(size=(5, 5)))
    axis.set_ylabel("y-axis")
    axis.set_xlabel("x-axis")
    axis.matshow(np.random.random(size=(5, 5)))

plt.show()


fig, ax = plt.subplots(1, 1, figsize=(formatter.width, formatter.width), sharex=True, sharey=True)
ax.matshow(np.random.random(size=(5, 5)))
ax.set_ylabel("y-axis")
ax.set_xlabel("x-axis")
plt.show()
```

![Unknown-1](https://user-images.githubusercontent.com/6968324/94171745-eaba1c80-fe91-11ea-985f-1cd7284c04ba.png)

![Unknown-2](https://user-images.githubusercontent.com/6968324/94171758-ef7ed080-fe91-11ea-9642-0b047bc90d46.png)

![Unknown-3](https://user-images.githubusercontent.com/6968324/94171765-f1e12a80-fe91-11ea-95b8-77dca04eea75.png)

**Comment by quantshah** [comment]
This will free the user from requiring to always call your formatter to get the `fig` and basically allow your package to be used on any pre-existing matplotlib code with a one-liner initialisation at the top.

**Comment by johannesjmeyer** [comment]
Interesting. But I guess you would loose the correct font-size scaling in this case, wouldn't you? The central point of rsmf is to adjust the figure size so that when I put in fontsize=12 in matplotlib it will really appear as fontsize 12 in the LaTeX document, and for that I need control over the figure.

And can't you achieve the same effect as you had above when creating the figure object through `rsmf` and then calling the `subplots` method of the figure?

**Comment by johannesjmeyer** [comment]
I think a good solution would be to advertise that the above usage is possible and have formatters expose `columnwidth` and `wide_columnwidth` so that people who need more control can use this to build their own figures. As long as you go width these widths and the font sizes from the formatter your plot should look good and the relevant `rcParams` are set while parsing. What do you think @quantshah ?

**Comment by johannesjmeyer** [comment]
This possibility is now explained in the docs, c.f. PR #12
